using AssetStoreTools.Utility;
using AssetStoreTools.Validator.Data;
using AssetStoreTools.Validator.Services.Validation;
using AssetStoreTools.Validator.TestDefinitions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace AssetStoreTools.Validator.TestMethods
{
    internal class CheckPackageNaming : ITestScript
    {
        private const string ForbiddenCharacters = "~`!@#$%^&*()-_=+[{]}\\|;:'\",<>?/";
        private readonly string[] PathsToCheckForForbiddenCharacters = new string[]
        {
            // Note: use separator suffix
            "Assets/",
            "Assets/Editor/",
            "Assets/Plugins/",
            "Assets/Resources/",
            "Assets/StreamingAssets/",
            "Assets/WebGLTemplates/"
        };
        private readonly string[] ExcludedPaths = new string[]
        {
            "Assets/_TerrainAutoUpgrade/" // Path which may automatically be generated by Unity when upgrading from old versions
        };

        private class PathCheckResult
        {
            public Object[] InvalidDirectPaths;
            public Object[] InvalidLeadingUpPaths;
            public Object[] InvalidHybridPackages;
            public Object[] PotentiallyInvalidContent;

            public bool HasIssues => InvalidDirectPaths.Length > 0
                || InvalidLeadingUpPaths.Length > 0
                || InvalidHybridPackages.Length > 0
                || PotentiallyInvalidContent.Length > 0;
        }

        private GenericTestConfig _config;
        private IAssetUtilityService _assetUtility;

        // Constructor also accepts dependency injection of registered IValidatorService types
        public CheckPackageNaming(GenericTestConfig config, IAssetUtilityService assetUtility)
        {
            _config = config;
            _assetUtility = assetUtility;
        }

        public TestResult Run()
        {
            var result = new TestResult() { Status = TestResultStatus.Undefined };

            var checkResult = GetInvalidPathsInAssets(_config.ValidationPaths);

            if (checkResult.HasIssues)
            {
                result.Status = TestResultStatus.Warning;

                if (checkResult.InvalidDirectPaths.Length > 0)
                {
                    result.Status = TestResultStatus.VariableSeverityIssue;
                    result.AddMessage("The following assets appear to be artificially bumped up in the project hierarchy within commonly used folders", null, checkResult.InvalidDirectPaths);
                }

                if (checkResult.InvalidLeadingUpPaths.Length > 0)
                {
                    result.Status = TestResultStatus.VariableSeverityIssue;
                    result.AddMessage("Despite not being directly validated, this path would be automatically created by the Unity Importer when importing your package", null, checkResult.InvalidLeadingUpPaths);
                }

                if (checkResult.InvalidHybridPackages.Length > 0)
                {
                    result.Status = TestResultStatus.VariableSeverityIssue;
                    result.AddMessage("The following packages appear to be artificially bumped up in the Package hierarchy with their 'Display Name' configuration", null, checkResult.InvalidHybridPackages);
                }

                if (checkResult.PotentiallyInvalidContent.Length > 0)
                {
                    // Do not override previously set severities
                    result.AddMessage("It is recommended that nested package content refrains from starting with a special character", null, checkResult.PotentiallyInvalidContent);
                }
            }
            else
            {
                result.Status = TestResultStatus.Pass;
                result.AddMessage("All package asset names are valid!");
            }

            return result;
        }

        private PathCheckResult GetInvalidPathsInAssets(string[] validationPaths)
        {
            var invalidAssetPaths = GetAllInvalidAssetPaths(validationPaths);

            // Paths that are directly validated and fall within the top-level of the forbidden path
            // e.g.: Assets/* or Assets/Plugins/*
            var invalidDirectPaths = GetInvalidDirectPaths(invalidAssetPaths);

            // Remaining paths (within the validation context)
            var otherInvalidPaths = invalidAssetPaths.Where(x => !invalidDirectPaths.Contains(x));
            foreach (var path in invalidDirectPaths)
                invalidAssetPaths.Remove(path);

            // Paths that are not directly validated, but may end up creating an invalid path when imported
            // e.g.: Assets/_WorkDir/MyPackage when validating MyPackage
            var invalidLeadingUpPaths = GetInvalidLeadingUpPaths(validationPaths);

            // Hybrid package Display Names
            var invalidHybridPackages = GetInvalidHybridPackages(validationPaths);

            return new PathCheckResult()
            {
                InvalidDirectPaths = PathsToObjects(invalidDirectPaths),
                InvalidLeadingUpPaths = PathsToObjects(invalidLeadingUpPaths),
                InvalidHybridPackages = PathsToObjects(invalidHybridPackages),
                PotentiallyInvalidContent = PathsToObjects(invalidAssetPaths)
            };
        }

        private List<string> GetAllInvalidAssetPaths(string[] validationPaths)
        {
            var invalidAssetPaths = new List<string>();

            var assetPaths = new List<string>();
            assetPaths.AddRange(_config.ValidationPaths);
            assetPaths.AddRange(_assetUtility.GetAssetPathsFromAssets(validationPaths, AssetType.All));

            foreach (var path in assetPaths)
            {
                if (ExcludedPaths.Any(x => path.StartsWith(x) || PathsAreEqual(x, path)))
                    continue;

                var name = path.Split('/').Last();
                if (ForbiddenCharacters.Any(x => name.StartsWith(x.ToString())))
                    invalidAssetPaths.Add(path);
            }

            return invalidAssetPaths;
        }

        private bool PathsAreEqual(string pathA, string pathB)
        {
            var pathAWithSeparator = pathA.EndsWith("/") ? pathA : pathA + "/";
            var pathBWithSeparator = pathB.EndsWith("/") ? pathB : pathB + "/";
            return pathAWithSeparator.Equals(pathBWithSeparator);
        }

        private List<string> GetInvalidDirectPaths(List<string> invalidPaths)
        {
            var invalidDirectPaths = new List<string>();

            foreach (var forbiddenPath in PathsToCheckForForbiddenCharacters)
            {
                foreach (var invalidPath in invalidPaths)
                {
                    if (!invalidPath.StartsWith(forbiddenPath))
                        continue;

                    // Keep only the top-level file system entries within the forbidden path
                    var truncated = invalidPath.Remove(0, forbiddenPath.Length);
                    var truncatedSplit = truncated.Split('/');
                    if (truncatedSplit.Length != 1)
                        continue;

                    invalidDirectPaths.Add(invalidPath);
                }
            }

            return invalidDirectPaths;
        }

        private List<string> GetInvalidLeadingUpPaths(string[] validationPaths)
        {
            var leadingUpPaths = new List<string>();

            foreach (var forbiddenPath in PathsToCheckForForbiddenCharacters)
            {
                foreach (var validationPath in validationPaths)
                {
                    if (!validationPath.StartsWith(forbiddenPath))
                        continue;

                    // Check the first character of the path name relative to the forbidden path
                    var truncated = validationPath.Remove(0, forbiddenPath.Length);
                    if (!ForbiddenCharacters.Any(x => truncated.StartsWith(x.ToString())))
                        continue;

                    // If the top-level path has no nested children, it is the full validation path and not the path leading up to it
                    var truncatedSplit = truncated.Split('/');
                    if (truncatedSplit.Length <= 1)
                        continue;

                    var invalidTopLevelPath = forbiddenPath + truncatedSplit[0];
                    if (!leadingUpPaths.Contains(invalidTopLevelPath))
                        leadingUpPaths.Add(invalidTopLevelPath);
                }
            }

            return leadingUpPaths;
        }

        private List<string> GetInvalidHybridPackages(string[] validationPaths)
        {
            var invalidPackages = new List<string>();

            foreach(var validationPath in validationPaths)
            {
                if (!PackageUtility.GetPackageByManifestPath($"{validationPath}/package.json", out var package))
                    continue;

                var packageName = package.displayName;
                if (ForbiddenCharacters.Any(x => packageName.StartsWith(x.ToString())))
                {
                    invalidPackages.Add(validationPath);
                }
            }

            return invalidPackages;
        }

        private Object[] PathsToObjects(IEnumerable<string> paths)
        {
            var objects = new List<Object>();

            foreach (var path in paths)
            {
                var obj = _assetUtility.AssetPathToObject(path);
                if (obj != null)
                    objects.Add(obj);
            }

            return objects.ToArray();
        }
    }
}